#!/bin/bash

DIRECC=/home/capecchi/SyncDir/build-moloch-with-gfortran/eccodes/eccodes-gfortran-installdir
# ifort
# OPT="-ip -O3 -W0 -warn none -xHost"
# gfortran
OPT="-flto -O3 -w -Wall -Wextra"
DIRVER=v22/

rm -f premoloch.exe

echo
echo "VERSION: "
readlink -f version 
echo
echo "PREMOLOCH: "
readlink -f premoloch.F90
echo
echo "DIMENSIONS: "
readlink -f dimensions.inc
echo
echo "COMPILING.....takes some minutes..."

FC=gfortran 
$FC -c $OPT -I${DIRECC}/include -L${DIRECC}/lib -leccodes_f90 -leccodes $DIRVER/read_grib2_data.F90 -o read_grib2_data.o
$FC -c $OPT $DIRVER/common_routines.F90 -o common_routines.o
$FC -c $OPT premoloch.F90 -o premoloch.o
$FC $OPT premoloch.o common_routines.o read_grib2_data.o -L${DIRECC}/lib -leccodes_f90 -leccodes -o premoloch.exe

rm *.mod *.o

echo
echo "All done.."

exit
