#!/bin/bash

RE=/home/capecchi/SyncDir/MOLOCH/tmp/rad_ecmwf

VERSION=`readlink -f version`
MODEL=`readlink -f moloch.F90`
DOMAIN=`readlink -f dimensions.inc`

[ -z $MODEL ] && { echo "Missing moloch.F90 link... exit"; exit; }

echo
echo "VERSION: " 
echo $VERSION
echo
echo "MODEL: " 
echo $MODEL
echo
echo "DOMAIN:"
#echo ${DOMAIN::-15}
echo
echo "DIMENSIONS: " 
cat dimensions.inc
echo

echo "START COMPILING..." 
echo

# ifort
COPT="-ip -O3 -warn none -vec-report0 -W0 -assume cc_omp"
# gfortran
COPT="-flto -O3 -w -fopenmp -Wall -Wextra -fallow-argument-mismatch"

mpif90 $COPT -D split -D splitshf -o moloch.o -c -I$RE/module -I$RE/module_aux -I$RE/include moloch.F90
mpif90 $COPT -D split -D splitshf -o moloch.exe moloch.o $RE/source/*.o $RE/module/*.o $RE/module_aux/*.o

rm *.mod *.o

echo "DONE!" 
echo

exit
